blog/urls.py
from blog import views
from blog.apps import BlogConfig
from django.urls import path
app_name = BlogConfig.name
urlpatterns = [
    path("create/", views.ArticleCreateView.as_view(), name="article_create"),
    path("publications/<int:pk>/", views.ArticleDetailView.as_view(), name="article_detail"),
    path("<int:pk>/update/", views.ArticleUpdateView.as_view(), name="article_update"),
    path("<int:pk>/delete/", views.ArticleDeleteView.as_view(), name="article_delete"),
    path("<str:status>/", views.ArticleListView.as_view(), name="article_list"),
]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog import views
from django.views.decorators.cache import cache_page

app_name = CatalogConfig.name

urlpatterns = [
    path("home/", views.HomeListView.as_view(), name="home"),
    path("unpublished-products/", views.UnpublishedProductsListView.as_view(), name="unpublished_products"),
    path("contacts/", views.ContactsTemplateView.as_view(), name="contacts"),
    path(
        "category-<str:category_name>/",
        views.CategoryProductsListView.as_view(),
        name="category_products",
    ),
    path("user-products/", views.UserProductsListView.as_view(), name="user_products"),
    path("product-create/", views.ProductCreateView.as_view(), name="product_create"),
    path("product-detail/<int:pk>/", cache_page(60 * 15)(views.ProductDetailView.as_view()), name="product_detail"),
    path("product-update/<int:pk>/", views.ProductUpdateView.as_view(), name="product_update"),
    path("product-delete/<int:pk>/", views.ProductDeleteView.as_view(), name="product_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogs/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("users-update/<int:pk>/", views.UserUpdateView.as_view(), name="user_update"),
]

catalog/models.py
from django.db import models
from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование")  # наименование
    description = models.TextField(verbose_name="Описание")  # описание

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ["name"]


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование")  # наименование
    description = models.TextField(verbose_name="Описание")  # описание
    image = models.ImageField(
        blank=True,
        null=True,
        upload_to="catalog/images/",
        verbose_name="Изображение",
    )  # изображение
    category = models.ForeignKey(
        Category,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="категория",
        related_name="products",
    )  # категория
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name="Цена за покупку",
    )  # цена за покупку
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Владелец", related_name="products", )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")  # дата создания
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")  # дата последнего изменения
    is_published = models.BooleanField(
        default=False,
        verbose_name="Статус публикации",
        help_text="Опубликовать продукт",
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        permissions = [
            ("can_unpublish_product", "Can unpublish product"),
        ]


class Contact(models.Model):
    country = models.CharField(
        max_length=60,
        verbose_name="Country",
        help_text="Введите название страны"
    )
    tin = models.CharField(
        max_length=20,
        verbose_name="Tax Identification Number",
        help_text="Введите ИНН"
    )
    address = models.TextField(
        verbose_name="Address",
        help_text="Введите адрес")

    def __str__(self):
        return self.country

    class Meta:
        verbose_name = "contact"
        verbose_name_plural = "contacts"

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Product
from .utils.mixins import StyleFormMixin
from .utils.validations_utils import check_input, make_warning, convert_size


class ProductForm(StyleFormMixin, forms.ModelForm):
    BANNED_WORDS = [
        "казино", "криптовалюта", "крипта",
        "биржа", "дешево", "бесплатно",
        "обман", "полиция", "радар",
    ]
    FIELDS_WITH_ATTRIBUTES = {
        "name": {"class": "form-control", "placeholder": "Введите название продукта"},
        "description": {"class": "form-control", "placeholder": "Введите описание продукта"},
        "image": {"class": "form-control"},
        "category": {"class": "form-control"},
        "price": {"class": "form-control", "placeholder": "Введите цену товара"},
    }
    # VALID_TYPES = ["image/jpeg", "image/png"]  # Допускаются файлы с форматами JPEG или PNG
    # IMAGE_SIZE_LIMIT = 5.0  # Допускаются файлы размером до 5 МБ

    class Meta:
        model = Product
        exclude = ["created_at", "updated_at", "is_published", "owner"]

    def clean_name(self):
        name = self.cleaned_data.get("name", "")
        banned_input = check_input(name, self.BANNED_WORDS)  # Поиск запрещенных слов
        if banned_input:
            raise ValidationError(make_warning(banned_input))
        return name

    def clean_description(self):
        description = self.cleaned_data.get("description", "")
        banned_input = check_input(description, self.BANNED_WORDS)  # Поиск запрещенных слов
        if banned_input:
            raise ValidationError(make_warning(banned_input))
        return description

    # def clean_image(self):
    #     image = self.cleaned_data.get("image")
    #     if image:
    #         image_format = image.content_type
    #         if image_format not in self.VALID_TYPES:
    #             raise ValidationError(f"Формат вашего файла – {image_format.split('/')[1].upper()}! "
    #                                   f"Допустимые форматы: JPEG и PNG.")
    #
    #         image_size = convert_size(image.size)
    #         if image_size > self.IMAGE_SIZE_LIMIT:
    #             raise ValidationError(f"Размер вашего файла: {image_size} МБ! Изображение не должно превышать "
    #                                   f"{self.IMAGE_SIZE_LIMIT} МБ.")
    #     return image

    def clean_price(self):
        price = self.cleaned_data.get("price", -1)
        if price < 0:
            raise ValidationError("Цена не может быть отрицательной!")
        return price

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy

from .forms import ProductForm
from catalog.models import Product
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog import services

class HomeListView(ListView):
    model = Product
    template_name = "catalog/home.html"

    def get_queryset(self):
        # return Product.objects.order_by("-created_at")
        return services.get_products_list_from_cache("publication", True, "published_products")


class ContactsTemplateView(TemplateView):
    template_name = "catalog/contacts.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return services.get_contact_info(context_data)

    def post(self, request):
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        print(f"Имеется новое сообщение от {name} {phone}: {message}")
        context_data = self.get_context_data()
        context_data["message"] = f"Спасибо, {name}! Сообщение получено :)"
        return self.render_to_response(context_data)


class CategoryProductsListView(ListView):
    model = Product
    template_name = "catalog/category_products.html"
    category_name = None

    def get_queryset(self):
        category_key = self.kwargs.get("category_name")
        self.category_name, queryset = services.get_products_by_category(category_key)
        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return services.set_context_data(context=context_data, category_name=self.category_name)


class UnpublishedProductsListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'catalog/products_list.html'

    def get_queryset(self):
        user = self.request.user
        queryset = services.get_products_list_from_cache("publication", False, "unpublished_products")
        return services.get_unpublished_products(queryset, user)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return services.set_context_data(context_data, title="Неопубликованное", header="Неопубликованные продукты")


class UserProductsListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = "catalog/products_list.html"

    def get_queryset(self):
        user = self.request.user
        return services.get_products_list_from_cache(filter_by="owner", value=user)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return services.set_context_data(context_data, title="Продукты пользователя", header="Мои продукты")


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        user = self.request.user
        product = form.instance
        # Если пользователь является модератором
        if user.has_perm("catalog.can_unpublish_product") and not user.is_superuser:
            raise PermissionDenied
        product.owner = user
        if self.request.POST.get("action") == "publish":
            form.instance.is_published = True
        return super().form_valid(form)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_object(self):
        product = get_object_or_404(Product, pk=self.kwargs["pk"])
        user = self.request.user
        if user != product.owner and not user.has_perm("catalog.can_unpublish_product"):
            raise PermissionDenied
        return product

    def post(self, request, pk):
        product = self.get_object()
        if request.POST.get("action") == "unpublish":
            if not self.request.user.has_perm("catalog.can_unpublish_product"):
                raise PermissionDenied
            product.is_published = False
            product.save()
        return redirect("catalog:home")


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        user = self.request.user
        product = get_object_or_404(Product, pk=self.kwargs["pk"])

        if user != product.owner:
            raise PermissionDenied

        if self.request.POST.get("action") == "publish":
            form.instance.is_published = True
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        user = self.request.user
        product = self.get_object()
        if user != product.owner and not user.has_perm("catalog.can_unpublish_product"):
            raise PermissionDenied
        return super().form_valid(form)

catalog/templates/catalog/includes/header.html
<!-- Заголовок страницы -->
<header class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    {% if description %}
        <p class="lead">{{ description }}</p>
    {% endif %}
</header>

catalog/templates/catalog/includes/inc_products_list.html
<!-- Код для отображения списка товаров с помощью цикла -->
 <div class="row">
     {% for product in product_list %}
         <div class="col-4">
             <div class="card mb-4 box-shadow">
                 {% if user == product.owner or perms.catalog.can_unpublish_product %}
                     <a href="/product-detail/{{ product.pk }}/" class="text-dark text-decoration-none">
                 {% endif %}
                         <div class="card-header">
                     <h4 class="my-0 font-weight-normal">
                         {{ product.name|truncatechars:35 }}
                     </h4>
                 </div>
                         {% if user.is_authenticated %}
                     </a>
                 {% endif %}
                 <div class="card-body">
                     <h1 class="card-title pricing-card-title">${{ product.price }}</h1>
                     <p>{{ product.description|truncatechars:100 }}</p>
                     <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                 </div>
             </div>
         </div>
     {% endfor %}

catalog/templates/catalog/includes/navbar.html
{% load static %}
 <!-- Навигационная панель -->
 <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
     <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
     <nav class="ms-5 d-flex w-100 justify-content-between">
         <!-- Кнопки слева -->
         <div>
             <a class="p-2 btn btn-outline-primary" href="/home">Каталог</a>
             <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
             {% if user.is_authenticated %}
                 <a class="p-2 btn btn-outline-primary" href="/unpublished-products/">Неопубликованное</a>
                 {% if not perms.catalog.can_unpublish_product %}<a class="p-2 btn btn-outline-primary" href="/product-create/">Добавить продукт</a>{% endif %}
             {% endif %}
         </div>
         <!-- Пользователь справа -->
         <div class="dropdown ms-auto">
             <button class="btn btn-link p-0 border-0 d-flex align-items-center" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                 <!-- Аватарка или стандартная иконка -->
                 {% if user.avatar %}
                     <!-- Аватарка пользователя -->
                     <img src="{{ user.avatar.url }}" alt="User avatar"
                          style="width: 40px; height: 40px; cursor: pointer; border-radius: 50%; object-fit: cover;">
                 {% else %}
                     <!-- Стандартная иконка -->
                     <img src="{% static 'images/person-circle.svg' %}" alt="Person icon"
                          style="width: 40px; height: 40px; cursor: pointer;">
                 {% endif %}
                 <!-- Почта пользователя -->
                 <span class="ms-2 text-body" style="cursor: pointer;">{{ user.email }}</span>
             </button>
             <!-- Выпадающее меню -->
             <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                 {% if user.is_authenticated %}
                    {% if not perms.catalog.can_unpublish_product %}
                     <li><a class="dropdown-item" href="{% url 'catalog:user_products' %}">Продукты</a></li>
                     <hr class="dropdown-divider">
                     {% endif %}
                     <li><a class="dropdown-item" href="/users/user-update/{{ user.pk }}/">Редактировать</a></li>
                     <li>
                         <form method="post" action="{% url 'users:logout' %}" class="d-inline">
                             {% csrf_token %}
                             <button type="submit" class="dropdown-item">Выйти</button>
                         </form>
                     </li>
                 {% else %}
                     <li><a class="dropdown-item" href="/users/login/">Вход</a></li>
                     <li><a class="dropdown-item" href="/users/register/">Регистрация</a></li>
                 {% endif %}
             </ul>
         </div>
     </nav>
 </div>

catalog/templates/catalog/includes/products_list.html
<!-- Код для отображения списка товаров с помощью цикла -->
 <div class="row">
     {% for product in product_list %}
         <div class="col-4">
             <div class="card mb-4 box-shadow">
                 {% if user.is_authenticated %}
                     <a href="/product-detail/{{ product.pk }}/" class="text-dark text-decoration-none">
                 {% endif %}
                         <div class="card-header">
                     <h4 class="my-0 font-weight-normal">
                         {{ product.name|truncatechars:35 }}
                     </h4>
                 </div>
                         {% if user.is_authenticated %}
                     </a>
                 {% endif %}
                 <div class="card-body">
                     <h1 class="card-title pricing-card-title">${{ product.price }}</h1>
                     <p>{{ product.description|truncatechars:100 }}</p>
                     <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                 </div>
             </div>
         </div>
     {% endfor %}