blog/urls.py
from blog import views
from blog.apps import BlogConfig
from django.urls import path
app_name = BlogConfig.name
urlpatterns = [
    path("create/", views.ArticleCreateView.as_view(), name="article_create"),
    path("publications/<int:pk>/", views.ArticleDetailView.as_view(), name="article_detail"),
    path("<int:pk>/update/", views.ArticleUpdateView.as_view(), name="article_update"),
    path("<int:pk>/delete/", views.ArticleDeleteView.as_view(), name="article_delete"),
    path("<str:status>/", views.ArticleListView.as_view(), name="article_list"),
]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog import views
from django.views.decorators.cache import cache_page

app_name = CatalogConfig.name

urlpatterns = [
    path("home/", views.HomeListView.as_view(), name="home"),
    path("unpublished-products/", views.UnpublishedProductsListView.as_view(), name="unpublished_products"),
    path("contacts/", views.ContactsTemplateView.as_view(), name="contacts"),
    path(
        "category-<str:category_name>/",
        views.CategoryProductsListView.as_view(),
        name="category_products",
    ),
    path("user-products/", views.UserProductsListView.as_view(), name="user_products"),
    path("product-create/", views.ProductCreateView.as_view(), name="product_create"),
    path("product-detail/<int:pk>/", cache_page(60 * 15)(views.ProductDetailView.as_view()), name="product_detail"),
    path("product-update/<int:pk>/", views.ProductUpdateView.as_view(), name="product_update"),
    path("product-delete/<int:pk>/", views.ProductDeleteView.as_view(), name="product_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogs/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from users.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование")  # наименование
    description = models.TextField(verbose_name="Описание")  # описание

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        ordering = ["name"]


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование")  # наименование
    description = models.TextField(verbose_name="Описание")  # описание
    image = models.ImageField(
        blank=True,
        null=True,
        upload_to="catalog/images/",
        verbose_name="Изображение",
    )  # изображение
    category = models.ForeignKey(
        Category,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="категория",
        related_name="products",
    )  # категория
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name="Цена за покупку",
    )  # цена за покупку
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Владелец", related_name="products", )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")  # дата создания
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")  # дата последнего изменения
    is_published = models.BooleanField(
        default=False,
        verbose_name="Статус публикации",
        help_text="Опубликовать продукт",
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        permissions = [
            ("can_unpublish_product", "Can unpublish product"),
        ]


class Contact(models.Model):
    country = models.CharField(
        max_length=60,
        verbose_name="Country",
        help_text="Введите название страны"
    )
    tin = models.CharField(
        max_length=20,
        verbose_name="Tax Identification Number",
        help_text="Введите ИНН"
    )
    address = models.TextField(
        verbose_name="Address",
        help_text="Введите адрес")

    def __str__(self):
        return self.country

    class Meta:
        verbose_name = "contact"
        verbose_name_plural = "contacts"

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Product
from .utils.mixins import StyleFormMixin
from .utils.validations_utils import check_input, make_warning, convert_size


class ProductForm(StyleFormMixin, forms.ModelForm):
    BANNED_WORDS = [
        "казино", "криптовалюта", "крипта",
        "биржа", "дешево", "бесплатно",
        "обман", "полиция", "радар",
    ]
    FIELDS_WITH_ATTRIBUTES = {
        "name": {"class": "form-control", "placeholder": "Введите название продукта"},
        "description": {"class": "form-control", "placeholder": "Введите описание продукта"},
        "image": {"class": "form-control"},
        "category": {"class": "form-control"},
        "price": {"class": "form-control", "placeholder": "Введите цену товара"},
    }
    # VALID_TYPES = ["image/jpeg", "image/png"]  # Допускаются файлы с форматами JPEG или PNG
    # IMAGE_SIZE_LIMIT = 5.0  # Допускаются файлы размером до 5 МБ

    class Meta:
        model = Product
        exclude = ["created_at", "updated_at", "is_published", "owner"]

    def clean_name(self):
        name = self.cleaned_data.get("name", "")
        banned_input = check_input(name, self.BANNED_WORDS)  # Поиск запрещенных слов
        if banned_input:
            raise ValidationError(make_warning(banned_input))
        return name

    def clean_description(self):
        description = self.cleaned_data.get("description", "")
        banned_input = check_input(description, self.BANNED_WORDS)  # Поиск запрещенных слов
        if banned_input:
            raise ValidationError(make_warning(banned_input))
        return description

    # def clean_image(self):
    #     image = self.cleaned_data.get("image")
    #     if image:
    #         image_format = image.content_type
    #         if image_format not in self.VALID_TYPES:
    #             raise ValidationError(f"Формат вашего файла – {image_format.split('/')[1].upper()}! "
    #                                   f"Допустимые форматы: JPEG и PNG.")
    #
    #         image_size = convert_size(image.size)
    #         if image_size > self.IMAGE_SIZE_LIMIT:
    #             raise ValidationError(f"Размер вашего файла: {image_size} МБ! Изображение не должно превышать "
    #                                   f"{self.IMAGE_SIZE_LIMIT} МБ.")
    #     return image

    def clean_price(self):
        price = self.cleaned_data.get("price", -1)
        if price < 0:
            raise ValidationError("Цена не может быть отрицательной!")
        return price

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy

from .forms import ProductForm
from catalog.models import Product
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from catalog import services

class HomeListView(ListView):
    model = Product
    template_name = "catalog/home.html"

    def get_queryset(self):
        # return Product.objects.order_by("-created_at")
        return services.get_products_list_from_cache("publication", True, "published_products")


class ContactsTemplateView(TemplateView):
    template_name = "catalog/contacts.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return services.get_contact_info(context_data)

    def post(self, request):
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        print(f"Имеется новое сообщение от {name} {phone}: {message}")
        context_data = self.get_context_data()
        context_data["message"] = f"Спасибо, {name}! Сообщение получено :)"
        return self.render_to_response(context_data)


class CategoryProductsListView(ListView):
    model = Product
    template_name = "catalog/category_products.html"
    category_name = None

    def get_queryset(self):
        category_key = self.kwargs.get("category_name")
        self.category_name, queryset = services.get_products_by_category(category_key)
        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return services.set_context_data(context=context_data, category_name=self.category_name)


class UnpublishedProductsListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'catalog/products_list.html'

    def get_queryset(self):
        user = self.request.user
        queryset = services.get_products_list_from_cache("publication", False, "unpublished_products")
        return services.get_unpublished_products(queryset, user)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return services.set_context_data(context_data, title="Неопубликованное", header="Неопубликованные продукты")


class UserProductsListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = "catalog/products_list.html"

    def get_queryset(self):
        user = self.request.user
        return services.get_products_list_from_cache(filter_by="owner", value=user)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return services.set_context_data(context_data, title="Продукты пользователя", header="Мои продукты")


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        user = self.request.user
        product = form.instance
        # Если пользователь является модератором
        if user.has_perm("catalog.can_unpublish_product") and not user.is_superuser:
            raise PermissionDenied
        product.owner = user
        if self.request.POST.get("action") == "publish":
            form.instance.is_published = True
        return super().form_valid(form)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_object(self):
        product = get_object_or_404(Product, pk=self.kwargs["pk"])
        user = self.request.user
        if user != product.owner and not user.has_perm("catalog.can_unpublish_product"):
            raise PermissionDenied
        return product

    def post(self, request, pk):
        product = self.get_object()
        if request.POST.get("action") == "unpublish":
            if not self.request.user.has_perm("catalog.can_unpublish_product"):
                raise PermissionDenied
            product.is_published = False
            product.save()
        return redirect("catalog:home")


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        user = self.request.user
        product = get_object_or_404(Product, pk=self.kwargs["pk"])

        if user != product.owner:
            raise PermissionDenied

        if self.request.POST.get("action") == "publish":
            form.instance.is_published = True
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:home")

    def form_valid(self, form):
        user = self.request.user
        product = self.get_object()
        if user != product.owner and not user.has_perm("catalog.can_unpublish_product"):
            raise PermissionDenied
        return super().form_valid(form)

catalog/templates/catalog/base.html
<!-- Базовый шаблон -->
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Base{% endblock %}</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
{% block header %}{% endblock %}

<div class="container">
    <!-- Основной контент -->
    {% block content %}{% endblock %}

    <!-- Подвал страницы -->
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <a class="text-decoration-none text-reset" href="/home">SkyStore</a>
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/category-mailing-lists/">Рассылки</a></li>
                    <li><a class="text-muted" href="/category-telegram-bots/">Телеграм Боты</a></li>
                    <li><a class="text-muted" href="/category-plugins">Плагины</a></li>
                    <li><a class="text-muted" href="/category-useful-utilities">Полезные утилиты</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/blogs/publications/">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<!-- Подключение Bootstrap JS -->
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/category_products.html
<!-- Шаблон для отображения списка товаров конкретной категории -->
{% extends "catalog/base.html" %}

{% block title %}{{ category_name }} · Skystore{% endblock %}

{% block header %}
{% include "catalog/includes/navbar.html" %}
{% endblock %}

{% block content %}
{% include "catalog/includes/header.html" with title="Skystore" %}
<h2>{{ category_name }}</h2>

{% if product_list %}
    {% include "catalog/includes/inc_products_list.html" %}
{% else %}
    <p>Пока здесь пусто, но скоро появятся новые товары. Следите за обновлениями!</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends "catalog/base.html" %}
{% block title %}Контакты · Skystore{% endblock %}

{% block header %}
{% include "catalog/includes/navbar.html" %}
{% endblock %}

{% block content %}
{% include "catalog/includes/header.html" with title="Контакты" %}
<div class="row text-start">
    <!-- Контактная информация -->
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>{{ contact_info.country }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>{{ contact_info.tin }}</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>{{ contact_info.address }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <!-- Сообщение об успешном заполнении формы -->
        <div class="mt-5 text-center">
            {% if message %}
                <p>{{ message }}</p>
            {% endif %}
        </div>
    </div>
     <!-- Форма обратной связи -->
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message" placeholder="Ваше сообщение" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
<!-- Шаблон главной страницы -->
{% extends "catalog/base.html" %}
{% block title %}Skystore{% endblock %}

{% block header %}{% include "catalog/includes/navbar.html" %}{% endblock %}

{% block content %}
{% include "catalog/includes/header.html" with title="Skystore" description="Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели продать" %}
<h2>Последние добавленные продукты</h2>

{% if product_list %}
    {% include "catalog/includes/inc_products_list.html" %}
{% else %}
    <p>Пока здесь пусто, но скоро появятся новые товары. Следите за обновлениями!</p>
{% endif %}

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends "catalog/base.html" %}
 
 {% block title %}Удаление продукта · Skystore{% endblock %}
 
 {% block header %}{% include "catalog/includes/navbar.html" %}{% endblock %}
 
 {% block content %}
     <div class="col-12 text-center my-5">
         <p>Действительно хотите удалить продукт <b>{{ object.name }}</b>?</p>
         <form method="post">
             {% csrf_token %}
             <button type="submit" class="btn btn-danger">Удалить</button>
             <a href="/product-detail/{{ object.pk }}/" class="btn btn-outline-secondary">Отмена</a>
         </form>
     </div>
 {% endblock %}

catalog/templates/catalog/product_detail.html
<!-- Шаблон для отображения страницы с подробной информацией о товаре -->
{% extends "catalog/base.html" %}
{% load my_tags %}
{% block title %}{{ product.name }} · Skystore{% endblock %}

{% block header %}
{% include "catalog/includes/navbar.html" %}
{% endblock %}

{% block content %}
{% include "catalog/includes/header.html" with title="Skystore" %}
<div class="row">
    <!-- Левая колонка (отступ) -->
    <div class="col-1"></div>

        <!-- Карточка -->
        <div class="card text-center">
            <!-- Заголовок карточки -->
            <div class="card-header">
                <h4 class="my-0 font-weight-normal text-center">{{ product.name }}</h4>
            </div>
            <!-- Контент карточки -->
            <div class="card-body">
                <img src="{{ product.image|media_filter }}" alt="{{ product.name }}" style="height: 200px;">
                <h5 class="card-title">Категория: {{ product.category }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <!-- Блок кнопок -->
                <div class="d-flex justify-content-start gap-2 mt-3">
                    {% if perms.catalog.can_unpublish_product %}
                        {% if product.is_published %}
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit" name="action" value="unpublish" class="btn btn-outline-danger">Отменить публикацию</button>
                        </form>
                        {% endif %}
                    {% else %}
                        <a class="p-2 btn btn-outline-primary" href="/product-update/{{ product.pk }}/">Редактировать</a>
                    {% endif %}
                    <a class="p-2 btn btn-outline-danger" href="/product-delete/{{ product.pk }}/">Удалить</a>
                </div>
            </div>
            <!-- Футер -->
            <div class="card-footer text-body-secondary">
                <b>Дата последнего изменения:</b> {{ product.updated_at|date:"d.m.Y" }}
            </div>
        </div>
</div>

    <!-- Правая колонка (отступ) -->
    <div class="col-1"></div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends "catalog/base.html" %}
 
 {% block title %}Форма продукта · Skystore{% endblock %}
 
 {% block header %}{% include "catalog/includes/navbar.html" %}{% endblock %}
 
 {% block content %}
 <h1 class="mb-3 mt-4">Форма продукта</h1>
 <form method="post" enctype="multipart/form-data">
     {% csrf_token %}
     {{ form.non_field_errors }}
     {{ form.as_p }}
        {% if product %}
            {% if not product.is_published %}
                <button type="submit" name="action" value="publish" class="btn btn-success">Опубликовать</button>
            {% endif %}
                <button type="submit" class="btn btn-outline-primary">Сохранить</button>
                <a href="{% url 'catalog:product_detail' product.pk %}" class="btn btn-outline-secondary">Отмена</a>
        {% else %}
             <button type="submit" name="action" value="publish" class="btn btn-success">Опубликовать</button>
             <button type="submit" class="btn btn-outline-primary">Добавить</button>
             <a href="{% url 'catalog:home' %}" class="btn btn-outline-secondary">Отмена</a>
        {% endif %}
 </form>
 {% endblock %}

catalog/templates/catalog/products_list.html
{% extends "catalog/base.html" %}
 
 {% block title %}{{ title }} · Skystore{% endblock %}
 
 {% block header %}{% include "catalog/includes/navbar.html" %}{% endblock %}
 
 {% block content %}
 <h2 class="mb-3">{{ header }}</h2>
 {% if product_list %}
     {% include "catalog/includes/inc_products_list.html" %}
 {% else %}
     <p>Продукты пока не добавлены</p>
 {% endif %}
 {% endblock %}